#!/usr/bin/env python3
"""
paper_figures.py — a small set of paper-grade ITE / TTE / energy-to-solution
figures built only from result cells with enough independent seeds to support
a real statistical claim (no best-of, no cherry-picking, censoring reported
where runs don't reach threshold within their iteration budget).

Each figure documents, in its own header comment, exactly which result files
back it and why that cell was chosen (matched hyperparameters across the
compared arms, consistent physics instance, seed depth).

Output: plots/paper_figures/*.{png,pdf}
"""

import glob
import gzip
import json
import os
import statistics

import matplotlib.pyplot as plt
import numpy as np

OUT_DIR = "plots/paper_figures"

COLOR_BLUE = "#2a78d6"
COLOR_GREEN = "#008300"
COLOR_MAGENTA = "#e87ba4"
INK = "#0b0b0b"
MUTED = "#898781"
GRID = "#e1e0d9"


# ---------------------------------------------------------------------------
# Shared statistics helpers (ITE censoring convention matches scripts/ite/ite_run.py;
# Wilson CI matches scripts/exper/parallel_embedding_bench.py)
# ---------------------------------------------------------------------------

def compute_ite(energies, exact_energy, epsilon, window=10):
    """First iteration (1-indexed) where the causal rolling-mean relative
    error drops below epsilon. None if never reached within the recorded run."""
    for t in range(len(energies)):
        w_start = max(0, t - window + 1)
        mean_e = sum(energies[w_start:t + 1]) / (t - w_start + 1)
        if abs(mean_e - exact_energy) / abs(exact_energy) < epsilon:
            return t + 1
    return None


def wilson_ci(k, n, z=1.96):
    if n == 0:
        return (0.0, 1.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def median_iqr(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, None
    return (
        float(np.percentile(vals, 50)),
        float(np.percentile(vals, 25)),
        float(np.percentile(vals, 75)),
    )


def load(pattern):
    out = []
    for f in sorted(glob.glob(pattern)):
        with gzip.open(f) as fh:
            out.append(json.load(fh))
    return out


def style_axes(ax):
    ax.grid(axis="y", which="major", color=GRID, linewidth=0.8, zorder=0)
    ax.grid(axis="y", which="minor", color=GRID, linewidth=0.4, zorder=0, alpha=0.5)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    ax.spines["left"].set_color(MUTED)
    ax.spines["bottom"].set_color(MUTED)
    ax.tick_params(colors=MUTED)


def log_x_with_ticks(ax, sizes, rotation=0):
    """Log-x axis labeled only at the actual N values (no autogenerated
    3x10^1-style minor tick labels colliding with them)."""
    ax.set_xscale("log")
    ax.xaxis.set_minor_locator(plt.NullLocator())
    ax.xaxis.set_minor_formatter(plt.NullFormatter())
    ax.set_xticks(sizes)
    ax.set_xticklabels([str(n) for n in sizes], rotation=rotation)


# ---------------------------------------------------------------------------
# Figure 1 — ITE vs N, tfim_1d, TFIM critical point
#
# Data: results/tfim_1d/{25,36,49,64,81,100,121,144,169,196}/custom/{metropolis,gibbs,lsb}
#       h=1.0 (critical point), matched RBM (full, n_hidden=N), lr=0.01, reg=1e-5,
#       n_samples=1000, 300 SR iterations, 5-7 seeds per cell.
#
# IMPORTANT CONFOUND, verified in the raw configs: every archived LSB run has
# cem=True (Cross-Entropy adaptive beta_x scaling, see encoder.py) while every
# Metropolis/Gibbs run has cem=False — there is no cem-matched LSB data to
# compare against. Metropolis vs. Gibbs below is a true sampler-only match
# (identical everything else, cem=False for both). LSB is plotted separately,
# dashed/hollow, explicitly labeled "+CEM", because its apparent speed advantage
# cannot be attributed to the sampler alone with the data on disk.
#
# Epsilon=0.01 (1% relative error), rolling window=10 iterations (ite_run.py convention).
# Runs that never cross epsilon within the 300-iteration budget are censored,
# not dropped — shown as hollow markers at the iteration budget.
# ---------------------------------------------------------------------------

def fig1_ite_vs_n_tfim1d():
    sizes = [25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
    samplers = [
        ("metropolis", "Metropolis (cem=False)", COLOR_BLUE, "o", "-"),
        ("gibbs", "Gibbs (cem=False)", COLOR_GREEN, "s", "-"),
        ("lsb", "LSB +CEM (not sampler-matched)", COLOR_MAGENTA, "^", "--"),
    ]
    epsilon = 0.01
    n_iterations = 300

    fig, ax = plt.subplots(figsize=(8, 5.5))

    for method, label, color, marker, linestyle in samplers:
        med, lo, hi, ns, censored_x, censored_n = [], [], [], [], [], []
        for n in sizes:
            recs = load(f"results/tfim_1d/{n}/custom/{method}/result_1d_h1.0_rbmfull_nh{n}_lr0.01_reg1e-05_ns1000_seed*_iter*")
            if not recs:
                med.append(None); lo.append(None); hi.append(None); ns.append(0)
                continue
            ites = [compute_ite(r["history"]["energy"], r["exact_energy"], epsilon) for r in recs]
            reached = [v for v in ites if v is not None]
            ns.append(len(ites))
            if reached:
                m, l, h = median_iqr(reached)
                med.append(m); lo.append(l); hi.append(h)
            else:
                med.append(None); lo.append(None); hi.append(None)
            if len(reached) < len(ites):
                censored_x.append(n)
                censored_n.append(f"{len(reached)}/{len(ites)}")

        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        lo_v = [l for l in lo if l is not None]
        hi_v = [h for h in hi if h is not None]
        if xs:
            yerr = [[y - l for y, l in zip(ys, lo_v)], [h - y for y, h in zip(ys, hi_v)]]
            ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                        markersize=7, linewidth=1.6, capsize=3, zorder=3, linestyle=linestyle)

        # censored sizes: draw hollow marker at the iteration budget
        cx = [n for n in sizes if n not in xs]
        if cx:
            ax.scatter(cx, [n_iterations] * len(cx), marker=marker, facecolors="none",
                       edgecolors=color, s=55, linewidth=1.4, zorder=3)

    ax.axhline(n_iterations, color=MUTED, linestyle=":", linewidth=1)
    ax.text(sizes[-1], n_iterations * 1.03, "iteration budget (censored above)",
            fontsize=8, color=MUTED, ha="right")

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes, rotation=45)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"ITE — iterations to {epsilon*100:.0f}% relative error (median, IQR)")
    ax.set_title("Iterations-to-epsilon vs. system size\nTFIM 1D, critical point h=1.0, matched hyperparameters, no best-of")
    style_axes(ax)
    ax.legend(frameon=False, loc="lower right", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig1_ite_vs_n_tfim1d")


# ---------------------------------------------------------------------------
# Figure 2 — Wall-clock time-to-epsilon vs N, VeloxQ vs FPGA
#
# Data: results/sweeps100 + results/sweeps2000, tfim_1d, N=8..128, h=0.5,
#       matched hyperparameters (n_hidden=N, lr=0.08, reg=0.05, n_samples=200),
#       velox vs fpga. sweeps100/sweeps2000 pooled: verified the two campaigns
#       give different outcomes for identical (seed, config) pairs, so VeloxQ's
#       sampler is not seed-deterministic and the pooled ~40 runs/cell are
#       genuinely independent, not duplicated.
# A separate point marks the freshly re-tuned N=128 VeloxQ config from
# results/sweeps100_v2 + sweeps2000_v2 (n_hidden=305, from a dedicated 45-trial
# Optuna search) — shown as a distinct annotated marker, NOT connected to the
# matched velox/fpga line, since FPGA has no equivalently re-tuned config at
# N=128 and connecting them would misrepresent a hardware-vs-hardware claim
# as a hyperparameter-tuning artifact.
# ---------------------------------------------------------------------------

def fig2_tte_vs_n_velox_fpga():
    sizes = [8, 12, 16, 24, 32, 64, 128]
    epsilon = 0.01

    fig, ax = plt.subplots(figsize=(8, 5.5))

    solvers = [("velox", "VeloxQ (SA)", COLOR_BLUE, "o"), ("fpga", "FPGA", COLOR_GREEN, "s")]

    for solver, label, color, marker in solvers:
        med, lo, hi, censored_x = [], [], [], []
        for n in sizes:
            recs = [
                r for r in
                load(f"results/sweeps100/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                + load(f"results/sweeps2000/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                if r["config"]["n_hidden"] == n
                and abs(r["config"]["learning_rate"] - 0.08) < 1e-9
                and abs(r["config"]["regularization"] - 0.05) < 1e-9
                and r["config"]["n_samples"] == 200
            ]
            if not recs:
                med.append(None); lo.append(None); hi.append(None)
                continue
            times = []
            for r in recs:
                ite = compute_ite(r["history"]["energy"], r["exact_energy"], epsilon)
                if ite is not None:
                    cum_t = np.cumsum(r["history"]["sampling_time_s"])
                    times.append(float(cum_t[ite - 1]))
            n_total = len(recs)
            if times:
                m, l, h = median_iqr(times)
                med.append(m); lo.append(l); hi.append(h)
            else:
                med.append(None); lo.append(None); hi.append(None)
            if len(times) < n_total:
                censored_x.append(n)

        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        lo_v = [l for l in lo if l is not None]
        hi_v = [h for h in hi if h is not None]
        if xs:
            yerr = [[y - l for y, l in zip(ys, lo_v)], [h - y for y, h in zip(ys, hi_v)]]
            ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                        markersize=7, linewidth=1.6, capsize=3, zorder=3)
        cx = [n for n in sizes if n not in xs]
        if cx:
            # place censored markers just above the highest plotted value for visibility
            ymax = max(ys) if ys else 1.0
            ax.scatter(cx, [ymax * 3] * len(cx), marker=marker, facecolors="none",
                       edgecolors=color, s=55, linewidth=1.4, zorder=3)

    # re-tuned N=128 velox point (sweeps100_v2 + sweeps2000_v2), annotated separately
    recs = load("results/sweeps100_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*") + \
        load("results/sweeps2000_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*")
    times = []
    for r in recs:
        ite = compute_ite(r["history"]["energy"], r["exact_energy"], epsilon)
        if ite is not None:
            cum_t = np.cumsum(r["history"]["sampling_time_s"])
            times.append(float(cum_t[ite - 1]))
    if times:
        m, lo_r, hi_r = median_iqr(times)
        ax.errorbar([128], [m], yerr=[[m - lo_r], [hi_r - m]], marker="*", color="#eb6834",
                    markersize=16, linewidth=1.6, capsize=3, zorder=4,
                    label=f"VeloxQ, re-tuned (n={len(times)}/{len(recs)} reached)")
        ax.annotate("re-tuned\nhyperparameters\n(not matched to FPGA)",
                    xy=(128, m), xytext=(40, m * 0.35),
                    fontsize=8, color=MUTED, ha="center",
                    arrowprops=dict(arrowstyle="->", color=MUTED, linewidth=0.8))

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"TTE — wall-clock time to {epsilon*100:.0f}% relative error [s] (median, IQR)")
    ax.set_title("Time-to-epsilon vs. system size\nTFIM 1D, h=0.5, matched hyperparameters, VeloxQ vs. FPGA")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig2_tte_vs_n_velox_fpga")


# ---------------------------------------------------------------------------
# Figure 3 — Energy-to-solution (final relative error) vs N, two panels
#
# Panel A: same tfim_1d custom-sampler cells as Figure 1 (h=1.0, 300 iters).
# Panel B: same velox/fpga matched cells as Figure 2 (h=0.5, 100 iters),
#          plus the re-tuned N=128 VeloxQ point.
# Shows the residual-error scaling directly, independent of any epsilon choice.
# ---------------------------------------------------------------------------

def fig3_energy_to_solution_vs_n():
    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    # Panel A
    ax = axes[0]
    sizes = [25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
    samplers = [
        ("metropolis", "Metropolis (cem=False)", COLOR_BLUE, "o", "-"),
        ("gibbs", "Gibbs (cem=False)", COLOR_GREEN, "s", "-"),
        ("lsb", "LSB +CEM (not sampler-matched)", COLOR_MAGENTA, "^", "--"),
    ]
    for method, label, color, marker, linestyle in samplers:
        med, lo, hi = [], [], []
        for n in sizes:
            recs = load(f"results/tfim_1d/{n}/custom/{method}/result_1d_h1.0_rbmfull_nh{n}_lr0.01_reg1e-05_ns1000_seed*_iter*")
            errs = [abs(r["final_energy"] - r["exact_energy"]) / abs(r["exact_energy"]) for r in recs]
            m, l, h = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(h)
        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [h - y for y, h in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3, linestyle=linestyle)
    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes, rotation=45)
    ax.set_xlabel("System size N")
    ax.set_ylabel(r"Final relative error $|E_\mathrm{final}-E_\mathrm{exact}|/|E_\mathrm{exact}|$")
    ax.set_title("(A) TFIM critical point (h=1.0), 300 iterations")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    # Panel B
    ax = axes[1]
    sizes = [8, 12, 16, 24, 32, 64, 128]
    solvers = [("velox", "VeloxQ (SA)", COLOR_BLUE, "o"), ("fpga", "FPGA", COLOR_GREEN, "s")]
    for solver, label, color, marker in solvers:
        med, lo, hi = [], [], []
        for n in sizes:
            recs = [
                r for r in
                load(f"results/sweeps100/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                + load(f"results/sweeps2000/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                if r["config"]["n_hidden"] == n
                and abs(r["config"]["learning_rate"] - 0.08) < 1e-9
                and abs(r["config"]["regularization"] - 0.05) < 1e-9
                and r["config"]["n_samples"] == 200
            ]
            errs = [abs(r["final_energy"] - r["exact_energy"]) / abs(r["exact_energy"]) for r in recs]
            m, l, h = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(h)
        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [h - y for y, h in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3)

    recs = load("results/sweeps100_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*") + \
        load("results/sweeps2000_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*")
    errs = [abs(r["final_energy"] - r["exact_energy"]) / abs(r["exact_energy"]) for r in recs]
    m, l, h = median_iqr(errs)
    ax.errorbar([128], [m], yerr=[[m - l], [h - m]], marker="*", color="#eb6834",
                markersize=16, linewidth=1.6, capsize=3, zorder=4,
                label="VeloxQ, re-tuned")

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes)
    ax.set_xlabel("System size N")
    ax.set_title("(B) TFIM, h=0.5, 100 iterations")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    fig.suptitle("Energy-to-solution vs. system size (median, IQR; no best-of)", y=1.02)
    fig.tight_layout()
    _save(fig, "fig3_energy_to_solution_vs_n")


# ---------------------------------------------------------------------------
# Figure 4 — Ground-state success fraction vs N at the Majumdar-Ghosh point
#
# Data: results/heisenberg_j1j2_1d/{8,12,16}/custom/{exchange,gibbs,simulated_annealing}
#       at J2=0.5 (the maximally frustrated Majumdar-Ghosh point of the J1-J2
#       chain), 28-30 seeds per cell, 300 SR iterations. "Success" = final
#       relative error < 5% (loose threshold appropriate for this highly
#       degenerate point). Wilson score CI (scripts/exper/parallel_embedding_bench.py
#       convention). The story is a sharp, solver-dependent finite-size crossover
#       rather than smooth hardness scaling: Gibbs solves this point at every N
#       tested, Exchange only becomes reliable at N>=12, and simulated annealing
#       stays at 0% success until a sudden jump at N=16 — each solver has a
#       different crossover size, not a shared monotonic trend.
# ---------------------------------------------------------------------------

def fig4_success_fraction_heisenberg():
    sizes = [8, 12, 16]
    solvers = [
        ("exchange", "Exchange", COLOR_BLUE, "o"),
        ("gibbs", "Gibbs", COLOR_GREEN, "s"),
        ("simulated_annealing", "Simulated annealing", COLOR_MAGENTA, "^"),
    ]
    success_threshold = 0.05

    fig, ax = plt.subplots(figsize=(7.5, 5.5))

    for method, label, color, marker in solvers:
        fracs, los, his, ns = [], [], [], []
        for n in sizes:
            recs = load(f"results/heisenberg_j1j2_1d/{n}/custom/{method}/result_*_J20.5_*_seed*_iter*")
            errs = [abs(r["final_energy"] - r["exact_energy"]) / abs(r["exact_energy"]) for r in recs]
            k = sum(1 for e in errs if e < success_threshold)
            n_total = len(errs)
            ns.append(n_total)
            if n_total == 0:
                fracs.append(None); los.append(None); his.append(None)
                continue
            lo_ci, hi_ci = wilson_ci(k, n_total)
            fracs.append(k / n_total); los.append(lo_ci); his.append(hi_ci)

        xs = [n for n, f in zip(sizes, fracs) if f is not None]
        ys = [f for f in fracs if f is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in los if v is not None])],
                [h - y for y, h in zip(ys, [v for v in his if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=8, linewidth=1.8, capsize=4, zorder=3)
        for x, y, n_total in zip(xs, ys, ns):
            ax.annotate(f"n={n_total}", (x, y), textcoords="offset points",
                        xytext=(0, 8), fontsize=7, color=MUTED, ha="center")

    ax.set_xticks(sizes)
    ax.set_xticklabels([str(n) for n in sizes])
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"Ground-state success fraction (rel. error < {success_threshold*100:.0f}%), Wilson 95% CI")
    ax.set_title(
        "Solver-dependent finite-size crossover at the Majumdar-Ghosh point\n"
        "J1-J2 Heisenberg chain, J2/J1 = 0.5, 300 SR iterations"
    )
    style_axes(ax)
    ax.legend(frameon=False, loc="center right", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig4_success_fraction_heisenberg_mg_point")


def _save(fig, name):
    os.makedirs(OUT_DIR, exist_ok=True)
    for ext in ("png", "pdf"):
        path = os.path.join(OUT_DIR, f"{name}.{ext}")
        fig.savefig(path, dpi=150 if ext == "png" else None, bbox_inches="tight")
        print(f"wrote {path}")
    plt.close(fig)


if __name__ == "__main__":
    fig1_ite_vs_n_tfim1d()
    fig2_tte_vs_n_velox_fpga()
    fig3_energy_to_solution_vs_n()
    fig4_success_fraction_heisenberg()
