#!/usr/bin/env python3
"""
paper_figures.py — a small set of paper-grade ITE / TTE / energy-to-solution
figures built only from result cells with enough independent seeds to support
a real statistical claim (no best-of, no cherry-picking, censoring reported
where runs don't reach threshold within their iteration budget).

Each figure documents, in its own header comment, exactly which result files
back it and why that cell was chosen (matched hyperparameters across the
compared arms, consistent physics instance, seed depth).

Output: plots/paper_figures/*.{png,pdf}
"""

import glob
import gzip
import json
import os
import statistics

import matplotlib.pyplot as plt
import numpy as np

OUT_DIR = "plots/paper_figures"

COLOR_BLUE = "#2a78d6"
COLOR_GREEN = "#008300"
COLOR_MAGENTA = "#e87ba4"
INK = "#0b0b0b"
MUTED = "#898781"
GRID = "#e1e0d9"


# ---------------------------------------------------------------------------
# Shared statistics helpers (ITE censoring convention matches scripts/ite/ite_run.py;
# Wilson CI matches scripts/exper/parallel_embedding_bench.py)
# ---------------------------------------------------------------------------

def compute_ite(energies, exact_energy, size, epsilon, window=10):
    """First iteration (1-indexed) where the causal rolling-mean energy error
    PER SPIN (|E-E_exact|/N, not relative to |E_exact|) drops below epsilon.
    None if never reached within the recorded run.

    Per-spin error is the convention used elsewhere in this repo (dashboard.py,
    plot_hparam_search.py, plot_sparsity_ablation_floor.py) and is the fairer
    one when a comparison spans different h (energy density varies with h, so
    relative error implicitly rescales by a different reference at every h;
    per-spin error does not)."""
    for t in range(len(energies)):
        w_start = max(0, t - window + 1)
        mean_e = sum(energies[w_start:t + 1]) / (t - w_start + 1)
        if abs(mean_e - exact_energy) / size < epsilon:
            return t + 1
    return None


def wilson_ci(k, n, z=1.96):
    if n == 0:
        return (0.0, 1.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def median_iqr(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, None
    return (
        float(np.percentile(vals, 50)),
        float(np.percentile(vals, 25)),
        float(np.percentile(vals, 75)),
    )


def load(pattern):
    out = []
    for f in sorted(glob.glob(pattern)):
        with gzip.open(f) as fh:
            out.append(json.load(fh))
    return out


def style_axes(ax):
    ax.grid(axis="y", which="major", color=GRID, linewidth=0.8, zorder=0)
    ax.grid(axis="y", which="minor", color=GRID, linewidth=0.4, zorder=0, alpha=0.5)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    ax.spines["left"].set_color(MUTED)
    ax.spines["bottom"].set_color(MUTED)
    ax.tick_params(colors=MUTED)


def log_x_with_ticks(ax, sizes, rotation=0):
    """Log-x axis labeled only at the actual N values (no autogenerated
    3x10^1-style minor tick labels colliding with them)."""
    ax.set_xscale("log")
    ax.xaxis.set_minor_locator(plt.NullLocator())
    ax.xaxis.set_minor_formatter(plt.NullFormatter())
    ax.set_xticks(sizes)
    ax.set_xticklabels([str(n) for n in sizes], rotation=rotation)


# ---------------------------------------------------------------------------
# Figure 1 — ITE vs N, tfim_1d, TFIM critical point
#
# Data: results/tfim_1d/{25,36,49,64,81,100,121,144,169,196}/custom/{metropolis,gibbs,lsb}
#       h=1.0 (critical point), matched RBM (full, n_hidden=N), lr=0.01, reg=1e-5,
#       n_samples=1000, 300 SR iterations, 5-7 seeds per cell.
#
# IMPORTANT CONFOUND, verified in the raw configs: every archived LSB run has
# cem=True (Cross-Entropy adaptive beta_x scaling, see encoder.py) while every
# Metropolis/Gibbs run has cem=False — there is no cem-matched LSB data to
# compare against. Metropolis vs. Gibbs below is a true sampler-only match
# (identical everything else, cem=False for both). LSB is plotted separately,
# dashed/hollow, explicitly labeled "+CEM", because its apparent speed advantage
# cannot be attributed to the sampler alone with the data on disk.
#
# Epsilon=0.01 energy error PER SPIN (|E-E_exact|/N), rolling window=10
# iterations (ite_run.py convention). h=1.0 is fixed across every N here and
# the ground-state energy density is verified near-constant (-1.2733 to
# -1.2741 per spin across N=25..196), so this per-spin threshold is not just
# a relabeling of the old relative-error one -- it happens to reproduce the
# same censoring pattern (checked: Metropolis/Gibbs were already 0/5 reached
# at N>=64 under the old relative-error convention too).
# Runs that never cross epsilon within the 300-iteration budget are censored,
# not dropped — shown as hollow markers at the iteration budget.
# ---------------------------------------------------------------------------

def fig1_ite_vs_n_tfim1d():
    sizes = [25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
    samplers = [
        ("metropolis", "Metropolis (cem=False)", COLOR_BLUE, "o", "-"),
        ("gibbs", "Gibbs (cem=False)", COLOR_GREEN, "s", "-"),
        ("lsb", "LSB +CEM (not sampler-matched)", COLOR_MAGENTA, "^", "--"),
    ]
    epsilon = 0.01
    n_iterations = 300

    fig, ax = plt.subplots(figsize=(8, 5.5))

    for method, label, color, marker, linestyle in samplers:
        med, lo, hi, ns, censored_x, censored_n = [], [], [], [], [], []
        for n in sizes:
            recs = load(f"results/tfim_1d/{n}/custom/{method}/result_1d_h1.0_rbmfull_nh{n}_lr0.01_reg1e-05_ns1000_seed*_iter*")
            if not recs:
                med.append(None); lo.append(None); hi.append(None); ns.append(0)
                continue
            ites = [compute_ite(r["history"]["energy"], r["exact_energy"], n, epsilon) for r in recs]
            reached = [v for v in ites if v is not None]
            ns.append(len(ites))
            if reached:
                m, l, h = median_iqr(reached)
                med.append(m); lo.append(l); hi.append(h)
            else:
                med.append(None); lo.append(None); hi.append(None)
            if len(reached) < len(ites):
                censored_x.append(n)
                censored_n.append(f"{len(reached)}/{len(ites)}")

        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        lo_v = [l for l in lo if l is not None]
        hi_v = [h for h in hi if h is not None]
        if xs:
            yerr = [[y - l for y, l in zip(ys, lo_v)], [h - y for y, h in zip(ys, hi_v)]]
            ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                        markersize=7, linewidth=1.6, capsize=3, zorder=3, linestyle=linestyle)

        # censored sizes: draw hollow marker at the iteration budget
        cx = [n for n in sizes if n not in xs]
        if cx:
            ax.scatter(cx, [n_iterations] * len(cx), marker=marker, facecolors="none",
                       edgecolors=color, s=55, linewidth=1.4, zorder=3)

    ax.axhline(n_iterations, color=MUTED, linestyle=":", linewidth=1)
    ax.text(sizes[-1], n_iterations * 1.03, "iteration budget (censored above)",
            fontsize=8, color=MUTED, ha="right")

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes, rotation=45)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"ITE — iterations to {epsilon:.3g} energy error/spin (median, IQR)")
    ax.set_title("Iterations-to-epsilon vs. system size\nTFIM 1D, critical point h=1.0, matched hyperparameters, no best-of")
    style_axes(ax)
    ax.legend(frameon=False, loc="lower right", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig1_ite_vs_n_tfim1d")


# ---------------------------------------------------------------------------
# Figure 2 — Wall-clock time-to-epsilon vs N, VeloxQ vs FPGA
#
# Data: results/sweeps100 + results/sweeps2000, tfim_1d, N=8..128, h=0.5,
#       matched hyperparameters (n_hidden=N, lr=0.08, reg=0.05, n_samples=200),
#       velox vs fpga. sweeps100/sweeps2000 pooled: verified the two campaigns
#       give different outcomes for identical (seed, config) pairs, so VeloxQ's
#       sampler is not seed-deterministic and the pooled ~40 runs/cell are
#       genuinely independent, not duplicated.
# A separate point marks the freshly re-tuned N=128 VeloxQ config from
# results/sweeps100_v2 + sweeps2000_v2 (n_hidden=305, from a dedicated 45-trial
# Optuna search) — shown as a distinct annotated marker, NOT connected to the
# matched velox/fpga line, since FPGA has no equivalently re-tuned config at
# N=128 and connecting them would misrepresent a hardware-vs-hardware claim
# as a hyperparameter-tuning artifact.
#
# Epsilon=0.01 energy error PER SPIN (not relative to |E_exact|; see
# compute_ite docstring). h=0.5 is fixed across N here and the ground-state
# energy density is verified constant (-1.0635 to -1.0636 per spin across
# N=8..128), so this reproduces the same reach/censoring pattern the old
# relative-error convention gave (checked directly).
# ---------------------------------------------------------------------------

def fig2_tte_vs_n_velox_fpga():
    sizes = [8, 12, 16, 24, 32, 64, 128]
    epsilon = 0.01

    fig, ax = plt.subplots(figsize=(8, 5.5))

    solvers = [("velox", "VeloxQ (SA)", COLOR_BLUE, "o"), ("fpga", "FPGA", COLOR_GREEN, "s")]

    for solver, label, color, marker in solvers:
        med, lo, hi, censored_x = [], [], [], []
        for n in sizes:
            recs = [
                r for r in
                load(f"results/sweeps100/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                + load(f"results/sweeps2000/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                if r["config"]["n_hidden"] == n
                and abs(r["config"]["learning_rate"] - 0.08) < 1e-9
                and abs(r["config"]["regularization"] - 0.05) < 1e-9
                and r["config"]["n_samples"] == 200
            ]
            if not recs:
                med.append(None); lo.append(None); hi.append(None)
                continue
            times = []
            for r in recs:
                ite = compute_ite(r["history"]["energy"], r["exact_energy"], n, epsilon)
                if ite is not None:
                    cum_t = np.cumsum(r["history"]["sampling_time_s"])
                    times.append(float(cum_t[ite - 1]))
            n_total = len(recs)
            if times:
                m, l, h = median_iqr(times)
                med.append(m); lo.append(l); hi.append(h)
            else:
                med.append(None); lo.append(None); hi.append(None)
            if len(times) < n_total:
                censored_x.append(n)

        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        lo_v = [l for l in lo if l is not None]
        hi_v = [h for h in hi if h is not None]
        if xs:
            yerr = [[y - l for y, l in zip(ys, lo_v)], [h - y for y, h in zip(ys, hi_v)]]
            ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                        markersize=7, linewidth=1.6, capsize=3, zorder=3)
        cx = [n for n in sizes if n not in xs]
        if cx:
            # place censored markers just above the highest plotted value for visibility
            ymax = max(ys) if ys else 1.0
            ax.scatter(cx, [ymax * 3] * len(cx), marker=marker, facecolors="none",
                       edgecolors=color, s=55, linewidth=1.4, zorder=3)

    # re-tuned N=128 velox point (sweeps100_v2 + sweeps2000_v2), annotated separately
    recs = load("results/sweeps100_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*") + \
        load("results/sweeps2000_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*")
    times = []
    for r in recs:
        ite = compute_ite(r["history"]["energy"], r["exact_energy"], 128, epsilon)
        if ite is not None:
            cum_t = np.cumsum(r["history"]["sampling_time_s"])
            times.append(float(cum_t[ite - 1]))
    if times:
        m, lo_r, hi_r = median_iqr(times)
        ax.errorbar([128], [m], yerr=[[m - lo_r], [hi_r - m]], marker="*", color="#eb6834",
                    markersize=16, linewidth=1.6, capsize=3, zorder=4,
                    label=f"VeloxQ, re-tuned (n={len(times)}/{len(recs)} reached)")
        ax.annotate("re-tuned\nhyperparameters\n(not matched to FPGA)",
                    xy=(128, m), xytext=(40, m * 0.35),
                    fontsize=8, color=MUTED, ha="center",
                    arrowprops=dict(arrowstyle="->", color=MUTED, linewidth=0.8))

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"TTE — wall-clock time to {epsilon:.3g} energy error/spin [s] (median, IQR)")
    ax.set_title("Time-to-epsilon vs. system size\nTFIM 1D, h=0.5, matched hyperparameters, VeloxQ vs. FPGA")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig2_tte_vs_n_velox_fpga")


# ---------------------------------------------------------------------------
# Figure 3 — Energy-to-solution (final energy error per spin) vs N, two panels
#
# Panel A: same tfim_1d custom-sampler cells as Figure 1 (h=1.0, 300 iters).
# Panel B: same velox/fpga matched cells as Figure 2 (h=0.5, 100 iters),
#          plus the re-tuned N=128 VeloxQ point.
# Shows the residual-error scaling directly, independent of any epsilon choice.
#
# Metric: energy error PER SPIN, |E_final-E_exact|/N -- not relative to
# |E_exact| (see compute_ite docstring for why per-spin is the fairer metric).
# ---------------------------------------------------------------------------

def fig3_energy_to_solution_vs_n():
    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    # Panel A
    ax = axes[0]
    sizes = [25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
    samplers = [
        ("metropolis", "Metropolis (cem=False)", COLOR_BLUE, "o", "-"),
        ("gibbs", "Gibbs (cem=False)", COLOR_GREEN, "s", "-"),
        ("lsb", "LSB +CEM (not sampler-matched)", COLOR_MAGENTA, "^", "--"),
    ]
    for method, label, color, marker, linestyle in samplers:
        med, lo, hi = [], [], []
        for n in sizes:
            recs = load(f"results/tfim_1d/{n}/custom/{method}/result_1d_h1.0_rbmfull_nh{n}_lr0.01_reg1e-05_ns1000_seed*_iter*")
            errs = [abs(r["final_energy"] - r["exact_energy"]) / n for r in recs]
            m, l, h = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(h)
        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [h - y for y, h in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3, linestyle=linestyle)
    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes, rotation=45)
    ax.set_xlabel("System size N")
    ax.set_ylabel(r"Final energy error per spin  $|E_\mathrm{final}-E_\mathrm{exact}|/N$")
    ax.set_title("(A) TFIM critical point (h=1.0), 300 iterations")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    # Panel B
    ax = axes[1]
    sizes = [8, 12, 16, 24, 32, 64, 128]
    solvers = [("velox", "VeloxQ (SA)", COLOR_BLUE, "o"), ("fpga", "FPGA", COLOR_GREEN, "s")]
    for solver, label, color, marker in solvers:
        med, lo, hi = [], [], []
        for n in sizes:
            recs = [
                r for r in
                load(f"results/sweeps100/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                + load(f"results/sweeps2000/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*")
                if r["config"]["n_hidden"] == n
                and abs(r["config"]["learning_rate"] - 0.08) < 1e-9
                and abs(r["config"]["regularization"] - 0.05) < 1e-9
                and r["config"]["n_samples"] == 200
            ]
            errs = [abs(r["final_energy"] - r["exact_energy"]) / n for r in recs]
            m, l, h = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(h)
        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [h - y for y, h in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3)

    recs = load("results/sweeps100_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*") + \
        load("results/sweeps2000_v2/tfim_1d/128/velox/simulated_annealing/result_*seed*")
    errs = [abs(r["final_energy"] - r["exact_energy"]) / 128 for r in recs]
    m, l, h = median_iqr(errs)
    ax.errorbar([128], [m], yerr=[[m - l], [h - m]], marker="*", color="#eb6834",
                markersize=16, linewidth=1.6, capsize=3, zorder=4,
                label="VeloxQ, re-tuned")

    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes)
    ax.set_xlabel("System size N")
    ax.set_title("(B) TFIM, h=0.5, 100 iterations")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=9)

    fig.suptitle("Energy-to-solution vs. system size (median, IQR; no best-of)", y=1.02)
    fig.tight_layout()
    _save(fig, "fig3_energy_to_solution_vs_n")


# ---------------------------------------------------------------------------
# Figure 4 — Ground-state success fraction vs N at the Majumdar-Ghosh point
#
# Data: results/heisenberg_j1j2_1d/{8,12,16}/custom/{exchange,gibbs,simulated_annealing}
#       at J2=0.5 (the maximally frustrated Majumdar-Ghosh point of the J1-J2
#       chain), 28-30 seeds per cell, 300 SR iterations. "Success" = final
#       energy error per spin < 0.05 (loose threshold appropriate for this
#       highly degenerate point; ground-state energy density is exactly
#       -1.5/spin at every N here, and success/failure is strongly bimodal --
#       checked that this per-spin threshold gives identical success counts
#       to the old relative-error 5% threshold at every method/N cell).
#       Wilson score CI (scripts/exper/parallel_embedding_bench.py
#       convention). The story is a sharp, solver-dependent finite-size crossover
#       rather than smooth hardness scaling: Gibbs solves this point at every N
#       tested, Exchange only becomes reliable at N>=12, and simulated annealing
#       stays at 0% success until a sudden jump at N=16 — each solver has a
#       different crossover size, not a shared monotonic trend.
# ---------------------------------------------------------------------------

def fig4_success_fraction_heisenberg():
    sizes = [8, 12, 16]
    solvers = [
        ("exchange", "Exchange", COLOR_BLUE, "o"),
        ("gibbs", "Gibbs", COLOR_GREEN, "s"),
        ("simulated_annealing", "Simulated annealing", COLOR_MAGENTA, "^"),
    ]
    success_threshold = 0.05

    fig, ax = plt.subplots(figsize=(7.5, 5.5))

    for method, label, color, marker in solvers:
        fracs, los, his, ns = [], [], [], []
        for n in sizes:
            recs = load(f"results/heisenberg_j1j2_1d/{n}/custom/{method}/result_*_J20.5_*_seed*_iter*")
            errs = [abs(r["final_energy"] - r["exact_energy"]) / n for r in recs]
            k = sum(1 for e in errs if e < success_threshold)
            n_total = len(errs)
            ns.append(n_total)
            if n_total == 0:
                fracs.append(None); los.append(None); his.append(None)
                continue
            lo_ci, hi_ci = wilson_ci(k, n_total)
            fracs.append(k / n_total); los.append(lo_ci); his.append(hi_ci)

        xs = [n for n, f in zip(sizes, fracs) if f is not None]
        ys = [f for f in fracs if f is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in los if v is not None])],
                [h - y for y, h in zip(ys, [v for v in his if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=8, linewidth=1.8, capsize=4, zorder=3)
        for x, y, n_total in zip(xs, ys, ns):
            ax.annotate(f"n={n_total}", (x, y), textcoords="offset points",
                        xytext=(0, 8), fontsize=7, color=MUTED, ha="center")

    ax.set_xticks(sizes)
    ax.set_xticklabels([str(n) for n in sizes])
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("System size N")
    ax.set_ylabel(f"Ground-state success fraction (energy error/spin < {success_threshold:.2g}), Wilson 95% CI")
    ax.set_title(
        "Solver-dependent finite-size crossover at the Majumdar-Ghosh point\n"
        "J1-J2 Heisenberg chain, J2/J1 = 0.5, 300 SR iterations"
    )
    style_axes(ax)
    ax.legend(frameon=False, loc="center right", fontsize=9)

    fig.tight_layout()
    _save(fig, "fig4_success_fraction_heisenberg_mg_point")


# ---------------------------------------------------------------------------
# Figure 5 — Single-instance convergence, TFIM 1D, includes real D-Wave QPU
# sampling (pegasus, zephyr), no new QPU time used (archived runs only).
#
# Data: N=8 and N=16, h=0.5, rbmfull, lr=0.1, reg=0.001, ns=1000, seed=42,
# iter=300 — the only cell in the whole results tree where a classical
# sampler, VeloxQ, and both D-Wave QPU solvers (pegasus, zephyr) share
# identical (N, h, RBM, lr, reg, n_samples, seed). Exact filenames (not
# globs) are used below because several nominally-identical cells on disk
# contain more than one archived run under the same seed label (from
# different sweep campaigns); one verified case (tfim_2d, metropolis) shows
# these can converge to very different final energies, so silently picking
# one via a generic tie-break risks a hidden cherry-pick. Here we instead
# pin the exact file whose name matches the D-Wave runs' naming byte-for-byte.
# VeloxQ has no archived N=8 run at this config, so N=8 has 3 solvers only.
# Single seed per solver: this is a qualitative single-instance comparison,
# not a statistical claim. No wall-clock timing is recorded for the D-Wave
# QPU runs (history has no sampling_time_s), so this is energy-vs-iteration
# only, not a TTE plot.
# ---------------------------------------------------------------------------

def fig5_convergence_dwave_tfim1d():
    panels = [
        (8, [
            ("results/tfim_1d/8/custom/metropolis/result_1d_h0.5_rbmfull_nh8_lr0.1_reg0.001_ns1000_seed42_iter300_cem0.json.gz", "Metropolis", COLOR_BLUE, "-"),
            ("results/tfim_1d/8/dimod/pegasus/result_1d_h0.5_rbmfull_nh8_lr0.1_reg0.001_ns1000_seed42_iter300_cem0.json.gz", "D-Wave Pegasus (QPU)", COLOR_MAGENTA, "-"),
            ("results/tfim_1d/8/dimod/zephyr/result_1d_h0.5_rbmfull_nh8_lr0.1_reg0.001_ns1000_seed42_iter300_cem0.json.gz", "D-Wave Zephyr (QPU)", "#eb6834", "-"),
        ]),
        (16, [
            ("results/tfim_1d/16/custom/metropolis/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed42_iter300.json.gz", "Metropolis", COLOR_BLUE, "-"),
            ("results/tfim_1d/16/velox/velox/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed42_iter300.json.gz", "VeloxQ (SA)", COLOR_GREEN, "-"),
            ("results/tfim_1d/16/dimod/pegasus/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed42_iter300.json.gz", "D-Wave Pegasus (QPU)", COLOR_MAGENTA, "-"),
            ("results/tfim_1d/16/dimod/zephyr/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed42_iter300.json.gz", "D-Wave Zephyr (QPU)", "#eb6834", "-"),
        ]),
    ]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    for ax, (n, runs) in zip(axes, panels):
        for path, label, color, linestyle in runs:
            with gzip.open(path) as fh:
                r = json.load(fh)
            energies = np.array(r["history"]["energy"])
            exact = r["exact_energy"]
            err_per_spin = np.abs(energies - exact) / n
            n_budget = r["config"]["iterations"]
            plot_label = label if len(err_per_spin) == n_budget else f"{label} (stopped @ {len(err_per_spin)}/{n_budget})"
            ax.plot(np.arange(1, len(err_per_spin) + 1), err_per_spin, color=color, label=plot_label,
                    linewidth=1.6, linestyle=linestyle, zorder=3)
            if len(err_per_spin) < n_budget:
                ax.scatter([len(err_per_spin)], [err_per_spin[-1]], color=color, marker="x", s=40, zorder=4)
        ax.set_yscale("log")
        ax.set_xlabel("SR iteration")
        ax.set_title(f"N = {n}")
        style_axes(ax)
        ax.legend(frameon=False, loc="upper right", fontsize=9)

    axes[0].set_ylabel(r"Energy error per spin  $|E-E_\mathrm{exact}|/N$")
    fig.suptitle(
        "Single-instance convergence, TFIM 1D, h=0.5, matched hyperparameters\n"
        "(seed=42, single run per solver — not a statistical comparison)", y=1.03
    )
    fig.tight_layout()
    _save(fig, "fig5_convergence_dwave_tfim1d")


# ---------------------------------------------------------------------------
# Figure 6 — Energy-to-solution vs N, TFIM 2D, includes real D-Wave QPU
# sampling (pegasus, zephyr), no new QPU time used (archived runs only).
#
# Data: results/tfim_2d/{4,6,8}/{custom/metropolis, dimod/pegasus,
# dimod/zephyr}, rbmfull, lr=0.1, reg=0.001, ns=1000, iter=300, matched
# across all three sizes and both D-Wave solvers, three field strengths
# h=0.5/1.0/2.0. D-Wave has 2 independent QPU runs per cell (seed 1, 42);
# metropolis has 2-3 (archived runs sharing a nominal seed label are kept as
# separate samples rather than deduplicated, since one checked case shows
# they can converge to genuinely different final energies — treating them
# as independent is honest, picking one would be a hidden cherry-pick).
# With only 2-3 samples per point, the shown band is not a real IQR; it is
# the same median_iqr() convention as Figures 1/3, interpreted as a
# min/max-ish spread rather than a statistical distribution.
#
# Metric: energy error PER SPIN, |E_final-E_exact|/N_spins, where N_spins=n*n
# for this 2D lattice (n_hidden=n*n for the matched rbmfull cell here) --
# not relative to |E_exact|. This panel set spans three different h values,
# each with its own energy density, so per-spin error (not implicitly
# rescaled by a different reference per h) is the metric that keeps panels
# comparable on their own terms rather than flattened to look similar.
# ---------------------------------------------------------------------------

def fig6_energy_vs_n_tfim2d_dwave():
    sizes = [4, 6, 8]
    hs = [0.5, 1.0, 2.0]
    solvers = [
        ("custom/metropolis", "Metropolis", COLOR_BLUE, "o"),
        ("dimod/pegasus", "D-Wave Pegasus (QPU)", COLOR_MAGENTA, "^"),
        ("dimod/zephyr", "D-Wave Zephyr (QPU)", "#eb6834", "s"),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True)

    for ax, h in zip(axes, hs):
        for subdir, label, color, marker in solvers:
            med, lo, hi, ns = [], [], [], []
            for n in sizes:
                nh = n * n
                recs = [
                    r for r in load(f"results/tfim_2d/{n}/{subdir}/result_2d_h{h}_rbmfull_nh{nh}_lr0.1_reg0.001_ns1000_seed*_iter300*")
                    if r["config"]["n_hidden"] == nh
                ]
                errs = [abs(r["final_energy"] - r["exact_energy"]) / nh for r in recs]
                ns.append(len(errs))
                m, l, hh = median_iqr(errs)
                med.append(m); lo.append(l); hi.append(hh)
            xs = [n for n, m in zip(sizes, med) if m is not None]
            ys = [m for m in med if m is not None]
            lo_v = [v for v in lo if v is not None]
            hi_v = [v for v in hi if v is not None]
            if xs:
                yerr = [[y - l for y, l in zip(ys, lo_v)], [hh - y for y, hh in zip(ys, hi_v)]]
                ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                            markersize=7, linewidth=1.6, capsize=3, zorder=3)
            for x, n_total in zip(sizes, ns):
                if n_total:
                    ax.annotate(f"n={n_total}", (x, med[sizes.index(x)]), textcoords="offset points",
                                xytext=(0, 7), fontsize=6.5, color=color, ha="center")
        ax.set_yscale("log")
        ax.set_xticks(sizes)
        ax.set_xticklabels([str(n) for n in sizes])
        ax.set_xlabel("Linear size N (lattice N×N)")
        ax.set_title(f"h = {h}")
        style_axes(ax)

    axes[0].set_ylabel(r"Final energy error per spin  $|E_\mathrm{final}-E_\mathrm{exact}|/N_\mathrm{spins}$")
    axes[0].legend(frameon=False, loc="upper left", fontsize=8.5)
    fig.suptitle(
        "Energy-to-solution vs. system size, TFIM 2D, matched hyperparameters\n"
        "Metropolis vs. D-Wave QPU (Pegasus, Zephyr) — n=2-3 samples per point", y=1.04
    )
    fig.tight_layout()
    _save(fig, "fig6_energy_vs_n_tfim2d_dwave")


# ---------------------------------------------------------------------------
# Figure 7 — ITE and energy-to-solution vs N, classical solver comparison,
# with real statistical power (10-15 seeds per point, not 2-3).
#
# Data: results/tfim_1d/{4,8,16}/{custom/metropolis, dimod/simulated_annealing,
# dimod/tabu}, h=1.0, rbmfull, lr=0.1, reg=1e-05, ns=1000, iter=100, cem=0.
# dimod/simulated_annealing and dimod/tabu run through the SAME DimodSampler
# codepath used for the D-Wave QPU runs (sampler.py) -- they are the
# classical software analogs of the pegasus/zephyr methods, just executed on
# CPU instead of the QPU. This isolates "does annealing-style discrete
# sampling help vs. plain MCMC" from "does the actual QPU help vs. its own
# classical simulation" (the latter question is addressed separately in
# Figures 5-6, where QPU data is thin).
#
# Metric: energy error PER SPIN, |E_final-E_exact|/N -- not relative to
# |E_exact| (see compute_ite docstring). This matters most for panel B below,
# where h varies at fixed N: energy density here ranges from -1.06/spin at
# h=0.5 to -2.13/spin at h=2.0, so relative error implicitly rescales each
# h's numbers by a different reference -- per-spin error does not, and is
# the fairer metric for a same-N, cross-h comparison.
#
# Panel A: final energy error per spin vs. N (4, 8, 16), h=1.0, matched
# hyperparameters, seeds 1-10 (N=4,16) or 1-15 (N=8) -- no cherry-picking, no
# best-of. An iterations-to-epsilon panel was tried here first and dropped:
# at this cell's 100-iteration budget, individual per-seed histories are
# unstable (energy jumps to large positive values before settling, verified
# on several seeds), so an early iteration can spuriously satisfy even a
# loose epsilon by chance while the run is still far from converged --
# ITE would silently misrepresent those seeds as fast. Final energy error is
# not sensitive to this artifact and is the honest metric for this cell.
#
# Panel B: same three solvers and same rich 15-seeds-per-cell campaign, but
# swept across field strength h at fixed N=8 instead of across N (this is
# the only size with h=0.5/1.0/1.5/2.0 all archived at 15 seeds). This is
# not a size-scaling panel -- it is included because, at fixed size, no
# solver dominates across the whole field range: Metropolis is best at
# h=0.5 (median 0.040 err/spin) while Tabu is best at h=1.5-2.0 (median
# 0.32-0.37 err/spin, vs. 1.06-1.88 for Metropolis/SA there). That crossover
# is a genuine, well-powered (n=15) finding, not an artifact of panel A's issue.
# ---------------------------------------------------------------------------

def fig7_classical_scaling_tfim1d():
    solvers = [
        ("custom/metropolis", "Metropolis (MCMC)", COLOR_BLUE, "o"),
        ("dimod/simulated_annealing", "Simulated annealing (classical, dimod/neal)", COLOR_GREEN, "s"),
        ("dimod/tabu", "Tabu search (classical, dimod)", COLOR_MAGENTA, "^"),
    ]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    # Panel A: final energy error per spin vs N, h=1.0
    ax = axes[0]
    sizes = [4, 8, 16]
    for solver, label, color, marker in solvers:
        med, lo, hi, ns = [], [], [], []
        for n in sizes:
            recs = load(f"results/tfim_1d/{n}/{solver}/result_1d_h1.0_rbmfull_nh{n}_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz")
            ns.append(len(recs))
            errs = [abs(r["final_energy"] - r["exact_energy"]) / n for r in recs]
            m, l, h = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(h)
        xs = [n for n, m in zip(sizes, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [h - y for y, h in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3)
        for x, n_total in zip(sizes, ns):
            ax.annotate(f"n={n_total}", (x, med[sizes.index(x)]), textcoords="offset points",
                        xytext=(8, 0), fontsize=7, color=color, ha="left")
    ax.set_yscale("log")
    log_x_with_ticks(ax, sizes)
    ax.set_xlabel("System size N")
    ax.set_ylabel(r"Final energy error per spin  $|E_\mathrm{final}-E_\mathrm{exact}|/N$")
    ax.set_title("(A) vs. system size, h=1.0 (critical point)")
    style_axes(ax)
    ax.legend(frameon=False, loc="upper left", fontsize=8)

    # Panel B: final energy error per spin vs h, N=8 fixed
    ax = axes[1]
    hs = [0.5, 1.0, 1.5, 2.0]
    for solver, label, color, marker in solvers:
        med, lo, hi, ns = [], [], [], []
        for h_val in hs:
            recs = load(f"results/tfim_1d/8/{solver}/result_1d_h{h_val}_rbmfull_nh8_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz")
            ns.append(len(recs))
            errs = [abs(r["final_energy"] - r["exact_energy"]) / 8 for r in recs]
            m, l, hh = median_iqr(errs)
            med.append(m); lo.append(l); hi.append(hh)
        xs = [x for x, m in zip(hs, med) if m is not None]
        ys = [m for m in med if m is not None]
        yerr = [[y - l for y, l in zip(ys, [v for v in lo if v is not None])],
                [hh - y for y, hh in zip(ys, [v for v in hi if v is not None])]]
        ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                    markersize=7, linewidth=1.6, capsize=3, zorder=3)
        for x, n_total in zip(hs, ns):
            ax.annotate(f"n={n_total}", (x, med[hs.index(x)]), textcoords="offset points",
                        xytext=(0, 8), fontsize=7, color=color, ha="center")
    ax.set_yscale("log")
    ax.set_xticks(hs)
    ax.set_xlabel("Transverse field h")
    ax.set_ylabel(r"Final energy error per spin  $|E_\mathrm{final}-E_\mathrm{exact}|/N$")
    ax.set_title("(B) vs. field strength, N=8 fixed")
    style_axes(ax)
    ax.legend(frameon=False, loc="center left", fontsize=8)

    fig.suptitle(
        "Classical solver comparison, TFIM 1D, matched hyperparameters, 100 iterations\n"
        "MCMC vs. classical annealing/tabu (10-15 independent seeds per point, no best-of)", y=1.03
    )
    fig.tight_layout()
    _save(fig, "fig7_classical_scaling_tfim1d")


# ---------------------------------------------------------------------------
# Figure 8 — All solvers archived at N=16, TFIM 1D, each at its own
# best-available operating point.
#
# THIS IS NOT A HYPERPARAMETER-MATCHED COMPARISON. It was checked
# exhaustively (every config tuple in every solver directory, across the
# entire results/ tree) and no (h, rbm, lr, reg, n_samples, iterations)
# cell is shared by more than 3 of these solvers anywhere in the archive --
# FPGA and VeloxQ in particular never share a config with Metropolis,
# Gibbs, LSB, or the dimod classical/QPU methods at any size. Forcing a
# match would mean throwing away everything except 1-2 solvers per plot
# (Figures 5-7 do exactly that, deliberately). This figure instead shows
# each solver's own richest archived cell at N=16 side by side, so every
# solver that has ever been run at this size appears -- but each row's (h,
# hyperparameters, n) is different and is annotated directly on the plot.
# Reading a difference between rows as "solver A beats solver B" is only
# valid to the extent you also believe their respective operating points
# are each that solver's fair shot; that is a judgment call for the reader,
# not something this figure can adjudicate.
#
# Per-solver cell (all rbm=full, n_hidden=16 unless noted):
#   Metropolis / dimod-SA / dimod-Tabu : h=1.0, lr=0.1,  reg=1e-05, ns=1000, iter=100,  n=10 each (matches Figure 7A)
#   Gibbs                              : h=0.5, lr=0.01, reg=1e-05, ns=1000, iter=300, cem=False, n=6
#   LSB                                : h=0.5, lr=0.01, reg=1e-05, ns=1000, iter=300, cem=False, n=3
#                                        (cem=False picked deliberately -- LSB also has cem=True
#                                        archived runs at this exact cell; using cem=False avoids
#                                        the LSB+CEM confound flagged in Figure 1)
#   VeloxQ (SA) / FPGA                 : h=0.5, lr=0.08 (sweeps convention, matches Fig 2/3),
#                                        reg=0.05, ns=200, sweeps100+sweeps2000 pooled, n=40 runs
#                                        (20 unique seeds, each campaign independently verified
#                                        non-duplicate final energies -- same pooling as Figure 2/3)
#   D-Wave Pegasus / Zephyr (QPU)      : h=0.5, rbmfull, lr=0.1, reg=0.001, ns=1000, iter=300, n=2
#                                        (matches Figure 5/6's cell; real QPU, thin)
#
# Metric: energy error PER SPIN, |E_final-E_exact|/16 -- not relative to
# |E_exact|. N=16 is fixed for every row here, so this is just a constant
# divisor, but rows mix h=1.0 (density -1.2732/spin) and h=0.5 (density
# -1.0635/spin) cells, so it is not a no-op relative to the old convention.
# ---------------------------------------------------------------------------

def fig8_all_solvers_n16():
    rows = [
        ("Metropolis (MCMC)", "results/tfim_1d/16/custom/metropolis/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_BLUE),
        ("Gibbs (MCMC)", "results/tfim_1d/16/custom/gibbs/result_1d_h0.5_rbmfull_nh16_lr0.01_reg1e-05_ns1000_seed*_iter300_cem0_sigma1.0.json.gz", None, COLOR_BLUE),
        ("LSB (MCMC)", "results/tfim_1d/16/custom/lsb/result_1d_h0.5_rbmfull_nh16_lr0.01_reg1e-05_ns1000_seed*_iter300_cem0_sigma1.0.json.gz", None, COLOR_BLUE),
        ("Simulated annealing (dimod/neal)", "results/tfim_1d/16/dimod/simulated_annealing/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_GREEN),
        ("Tabu search (dimod)", "results/tfim_1d/16/dimod/tabu/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_GREEN),
        ("VeloxQ (SA hardware)", None, "velox", "#eb6834"),
        ("FPGA", None, "fpga", "#eb6834"),
        ("D-Wave Pegasus (QPU)", "results/tfim_1d/16/dimod/pegasus/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed*_iter300.json.gz", None, COLOR_MAGENTA),
        ("D-Wave Zephyr (QPU)", "results/tfim_1d/16/dimod/zephyr/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed*_iter300.json.gz", None, COLOR_MAGENTA),
    ]

    def sweeps_recs(solver):
        out = []
        for campaign in ("sweeps100", "sweeps2000"):
            for r in load(f"results/{campaign}/tfim_1d/16/{solver}/*/result_*_seed*_iter*"):
                c = r["config"]
                if c["n_hidden"] == 16 and abs(c["learning_rate"] - 0.08) < 1e-9 \
                        and abs(c["regularization"] - 0.05) < 1e-9 and c["n_samples"] == 200:
                    out.append(r)
        return out

    fig, ax = plt.subplots(figsize=(9, 6.5))
    ylabels = []
    for i, (label, pattern, sweep_solver, color) in enumerate(rows):
        recs = sweeps_recs(sweep_solver) if sweep_solver else load(pattern)
        errs = [abs(r["final_energy"] - r["exact_energy"]) / 16 for r in recs]
        m, lo, hi = median_iqr(errs)
        y = len(rows) - i
        if m is not None:
            ax.errorbar([m], [y], xerr=[[m - lo], [hi - m]], marker="o", color=color,
                        markersize=8, linewidth=1.6, capsize=4, zorder=3)
        ax.annotate(f"n={len(errs)}", (max(errs) if errs else 1, y), textcoords="offset points",
                    xytext=(8, 0), fontsize=7.5, color=color, va="center")
        ylabels.append(label)

    ax.set_yticks([len(rows) - i for i in range(len(rows))])
    ax.set_yticklabels(ylabels)
    ax.set_xscale("log")
    ax.set_xlabel(r"Final energy error per spin  $|E_\mathrm{final}-E_\mathrm{exact}|/N$ (median, IQR)")
    ax.set_title(
        "All archived solvers at N=16, each at its own best-available operating point\n"
        "NOT hyperparameter-matched -- see script comments for each row's (h, config, n)",
        fontsize=11
    )
    style_axes(ax)
    ax.grid(axis="x", which="major", color=GRID, linewidth=0.8, zorder=0)

    fig.tight_layout()
    _save(fig, "fig8_all_solvers_n16")


# ---------------------------------------------------------------------------
# Figure 9 — ITE and TTE, all solvers at N=16, each at its own best-available
# operating point (companion to Figure 8; same per-solver cells/config
# table, see Figure 8's header comment).
#
# Panel A (ITE): iterations to 0.01 energy error per spin, rolling window=10
# (ite_run.py convention). Solvers whose best-available cell never reaches
# threshold within its own iteration budget are censored (hollow marker at
# the recorded budget) rather than dropped -- for Metropolis and dimod-SA at
# their h=1.0/100-iteration cell this is a real result (that cell is a hard,
# short-budget regime), not a plotting gap.
#
# Panel B (TTE): wall-clock time to 0.01 energy error per spin, from
# cumulative per-iteration timing in each run's own history. Per CLAUDE.md's
# no-silent-fallback rule, a solver is only included here if its archived
# history actually records a timing field -- D-Wave Pegasus/Zephyr (QPU)
# results in this archive have NO per-iteration timing field at all (verified:
# 'sampling_time_s' is simply absent from their history dict), so they are
# omitted from panel B entirely rather than assigned a fabricated or
# assumed duration. Where a run logs both 'sampling_time_s' and
# 'total_sampling_time_s' (LSB, VeloxQ, FPGA -- these use CEM, so total
# includes cem_time_s), the 'total_*' field is used for a fair like-for-like
# wall-clock accounting; solvers without CEM only ever have 'sampling_time_s'.
# ---------------------------------------------------------------------------

def fig9_ite_tte_all_solvers_n16():
    epsilon = 0.01

    rows = [
        ("Metropolis (MCMC)", "results/tfim_1d/16/custom/metropolis/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_BLUE),
        ("Gibbs (MCMC)", "results/tfim_1d/16/custom/gibbs/result_1d_h0.5_rbmfull_nh16_lr0.01_reg1e-05_ns1000_seed*_iter300_cem0_sigma1.0.json.gz", None, COLOR_BLUE),
        ("LSB (MCMC)", "results/tfim_1d/16/custom/lsb/result_1d_h0.5_rbmfull_nh16_lr0.01_reg1e-05_ns1000_seed*_iter300_cem0_sigma1.0.json.gz", None, COLOR_BLUE),
        ("Simulated annealing (dimod/neal)", "results/tfim_1d/16/dimod/simulated_annealing/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_GREEN),
        ("Tabu search (dimod)", "results/tfim_1d/16/dimod/tabu/result_1d_h1.0_rbmfull_nh16_lr0.1_reg1e-05_ns1000_seed*_iter100_cem0.json.gz", None, COLOR_GREEN),
        ("VeloxQ (SA hardware)", None, "velox", "#eb6834"),
        ("FPGA", None, "fpga", "#eb6834"),
        ("D-Wave Pegasus (QPU)", "results/tfim_1d/16/dimod/pegasus/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed*_iter300.json.gz", None, COLOR_MAGENTA),
        ("D-Wave Zephyr (QPU)", "results/tfim_1d/16/dimod/zephyr/result_1d_h0.5_rbmfull_nh16_lr0.1_reg0.001_ns1000_seed*_iter300.json.gz", None, COLOR_MAGENTA),
    ]

    def sweeps_recs(solver):
        out = []
        for campaign in ("sweeps100", "sweeps2000"):
            for r in load(f"results/{campaign}/tfim_1d/16/{solver}/*/result_*_seed*_iter*"):
                c = r["config"]
                if c["n_hidden"] == 16 and abs(c["learning_rate"] - 0.08) < 1e-9 \
                        and abs(c["regularization"] - 0.05) < 1e-9 and c["n_samples"] == 200:
                    out.append(r)
        return out

    def time_field(r):
        h = r["history"]
        if "total_sampling_time_s" in h:
            return "total_sampling_time_s"
        if "sampling_time_s" in h:
            return "sampling_time_s"
        return None

    fig, axes = plt.subplots(1, 2, figsize=(15, 6.5))
    ylabels = []
    for i, (label, pattern, sweep_solver, color) in enumerate(rows):
        recs = sweeps_recs(sweep_solver) if sweep_solver else load(pattern)
        y = len(rows) - i
        ylabels.append(label)

        ites = [compute_ite(r["history"]["energy"], r["exact_energy"], 16, epsilon) for r in recs]
        reached_ite = [v for v in ites if v is not None]
        budgets = [len(r["history"]["energy"]) for r in recs]

        ax = axes[0]
        if reached_ite:
            m, lo, hi = median_iqr(reached_ite)
            ax.errorbar([m], [y], xerr=[[m - lo], [hi - m]], marker="o", color=color,
                        markersize=8, linewidth=1.6, capsize=4, zorder=3)
        if len(reached_ite) < len(recs) and budgets:
            ax.scatter([max(budgets)], [y], marker="x", color=color, s=60, zorder=4)
        ax.annotate(f"n={len(reached_ite)}/{len(recs)}", (max(budgets) if budgets else 1, y),
                    textcoords="offset points", xytext=(8, 0), fontsize=7.5, color=color, va="center")

        ax = axes[1]
        tf = time_field(recs[0]) if recs else None
        if tf is None:
            ax.annotate(f"{label}: no timing recorded", (0.02, y), xycoords=("axes fraction", "data"),
                        fontsize=8, color=MUTED, va="center", style="italic")
            continue
        cum_times = [np.cumsum(r["history"][tf]) for r in recs]
        ttes = [float(ct[ite - 1]) for ct, ite in zip(cum_times, ites) if ite is not None]
        totals = [float(ct[-1]) for ct in cum_times]
        if ttes:
            m, lo, hi = median_iqr(ttes)
            ax.errorbar([m], [y], xerr=[[m - lo], [hi - m]], marker="o", color=color,
                        markersize=8, linewidth=1.6, capsize=4, zorder=3)
        if len(ttes) < len(recs) and totals:
            ax.scatter([max(totals)], [y], marker="x", color=color, s=60, zorder=4)
        ax.annotate(f"n={len(ttes)}/{len(recs)}", (max(totals) if totals else 1, y),
                    textcoords="offset points", xytext=(8, 0), fontsize=7.5, color=color, va="center")

    for ax, xlabel, title in [
        (axes[0], f"ITE — iterations to {epsilon:.3g} energy error/spin (median, IQR; x = censored)", "(A) Iterations-to-epsilon"),
        (axes[1], f"TTE — wall-clock seconds to {epsilon:.3g} energy error/spin (median, IQR; x = censored)", "(B) Time-to-epsilon (QPU omitted, no timing recorded)"),
    ]:
        ax.set_yticks([len(rows) - i for i in range(len(rows))])
        ax.set_yticklabels(ylabels if ax is axes[0] else [])
        ax.set_xscale("log")
        ax.set_xlabel(xlabel, fontsize=9)
        ax.set_title(title, fontsize=10.5)
        ax.set_ylim(0.3, len(rows) + 0.7)
        style_axes(ax)
        ax.grid(axis="x", which="major", color=GRID, linewidth=0.8, zorder=0)

    fig.suptitle(
        "All archived solvers at N=16, each at its own best-available operating point\n"
        "NOT hyperparameter-matched -- see Figure 8 for each row's (h, config, n)", y=1.03
    )
    fig.tight_layout()
    _save(fig, "fig9_ite_tte_all_solvers_n16")


# ---------------------------------------------------------------------------
# Figure 10 — ITE and TTE vs. system size N, all solvers
# ---------------------------------------------------------------------------

def fig10_ite_tte_vs_n_all_solvers(epsilon=0.01):
    # Metropolis/Gibbs/LSB(+CEM) run at the exact same (lr, reg, n_samples,
    # iterations) cell as FPGA/VeloxQ's "sweeps100" campaign below (see
    # scripts/exper/mcmc_matched_sweep.py) -- this makes the comparison
    # hyperparameter-matched, not just h-matched.
    def mcmc_recs(solver, n, cem=0):
        recs = load(f"results/tfim_1d/{n}/custom/{solver}/result_1d_h0.5_rbmfull_nh{n}_lr0.08_reg0.05_ns200_seed*_iter100_cem{cem}_sigma1.0.json.gz")
        return [r for r in recs if r["config"]["n_hidden"] == n and abs(r["config"]["learning_rate"] - 0.08) < 1e-9
                and abs(r["config"]["regularization"] - 0.05) < 1e-9 and r["config"]["n_samples"] == 200
                and r["config"]["iterations"] == 100][:20]

    def sweeps_recs(solver, n):
        out = []
        for r in load(f"results/sweeps100/tfim_1d/{n}/{solver}/*/result_*_seed*_iter*"):
            c = r["config"]
            if c["n_hidden"] == n and abs(c["learning_rate"] - 0.08) < 1e-9 \
                    and abs(c["regularization"] - 0.05) < 1e-9 and c["n_samples"] == 200:
                out.append(r)
        return out[:20]

    def dwave_recs(method, n):
        recs = load(f"results/tfim_1d/{n}/dimod/{method}/result_1d_h0.5_rbmfull_nh{n}_lr*_reg0.001_ns1000_seed*_iter300*.json.gz")
        return [r for r in recs if r["config"]["n_hidden"] == n and abs(r["config"]["regularization"] - 0.001) < 1e-9]

    def velox_untuned_recs(n):
        with open("results/custom/velox_default_h0.5.json") as f:
            default = json.load(f)
        cfg = default["config"]
        out = []
        for campaign in default["source_campaigns"]:
            pattern = default["source_path_template"].format(campaign=campaign, n=n)
            for r in load(pattern):
                c = r["config"]
                if c["n_hidden"] == n and abs(c["learning_rate"] - cfg["learning_rate"]) < 1e-9 \
                        and abs(c["regularization"] - cfg["regularization"]) < 1e-9 and c["n_samples"] == cfg["n_samples"]:
                    out.append(r)
        return out[:20]

    _sizes = [8, 12, 16, 24, 32, 64, 128]
    series = [
        ("Metropolis", _sizes, lambda n: mcmc_recs("metropolis", n), COLOR_BLUE, "o", "-"),
        ("Gibbs", _sizes, lambda n: mcmc_recs("gibbs", n), COLOR_GREEN, "s", "-"),
        ("LSB", _sizes, lambda n: mcmc_recs("lsb", n, cem=0), COLOR_MAGENTA, "^", "--"),
        ("LSB (+CEM)", _sizes, lambda n: mcmc_recs("lsb", n, cem=1), "#a83279", "v", "--"),
        ("VeloxQ (SA, untuned)", _sizes, lambda n: velox_untuned_recs(n), "#eb6834", "P", "-"),
        ("FPGA", _sizes, lambda n: sweeps_recs("fpga", n), "#ffa600", "X", "-"),
    ]

    fig, ax = plt.subplots(figsize=(8, 6.5))

    for series_idx, (label, sizes, get_recs, color, marker, linestyle) in enumerate(series):
        tte_med, tte_lo, tte_hi, tte_n, tte_budget = [], [], [], [], []
        for n in sizes:
            recs = get_recs(n)
            timed_recs = [r for r in recs if "sampling_time_s" in r["history"] or "total_sampling_time_s" in r["history"]]
            if timed_recs:
                tf = "total_sampling_time_s" if "total_sampling_time_s" in timed_recs[0]["history"] else "sampling_time_s"
                cum_times = [np.cumsum(r["history"][tf]) for r in timed_recs]
                ites_timed = [compute_ite(r["history"]["energy"], r["exact_energy"], n, epsilon) for r in timed_recs]
                ttes = [float(ct[ite - 1]) for ct, ite in zip(cum_times, ites_timed) if ite is not None]
                m, l, h = median_iqr(ttes) if ttes else (None, None, None)
                tte_med.append(m); tte_lo.append(l); tte_hi.append(h)
                tte_n.append((len(ttes), len(recs)))
                tte_budget.append(max((float(ct[-1]) for ct in cum_times), default=None))
            else:
                tte_med.append(None); tte_lo.append(None); tte_hi.append(None)
                tte_n.append((0, 0)); tte_budget.append(None)

        xs = [n for n, m in zip(sizes, tte_med) if m is not None]
        ys = [m for m in tte_med if m is not None]
        lo_v = [v for v in tte_lo if v is not None]
        hi_v = [v for v in tte_hi if v is not None]
        if xs:
            yerr = [[y - l for y, l in zip(ys, lo_v)], [h - y for y, h in zip(ys, hi_v)]]
            ax.errorbar(xs, ys, yerr=yerr, marker=marker, color=color, label=label,
                        markersize=7, linewidth=1.5, capsize=3, zorder=3, linestyle=linestyle)
        else:
            ax.plot([], [], marker=marker, color=color, linestyle=linestyle, label=label)
        cx = [n for n, m, b in zip(sizes, tte_med, tte_budget) if m is None and b is not None]
        cb = [b * (1.0 + 0.05 * series_idx) for m, b in zip(tte_med, tte_budget) if m is None and b is not None]
        if cx:
            ax.scatter(cx, cb, marker=marker, facecolors="none", edgecolors=color, s=50, linewidth=1.3, zorder=3)
        for n, (r, total) in zip(sizes, tte_n):
            if total and r < total:
                y_pos = tte_budget[sizes.index(n)] if tte_med[sizes.index(n)] is None else tte_med[sizes.index(n)]
                if y_pos is not None:
                    ax.annotate(f"{r}/{total}", (n, y_pos), textcoords="offset points",
                                xytext=(4, 6), fontsize=6, color=color, ha="left")

    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_xlabel("System size N")
    style_axes(ax)
    ax.set_ylabel(f"TTE — wall-clock seconds to {epsilon:.3g} energy error/spin (median, IQR)")
    ax.set_title("Time-to-epsilon vs. N")
    ax.legend(frameon=False, loc="upper left", fontsize=7.5, ncol=2)

    fig.suptitle(
        "TTE vs. system size, all solvers\n"
        "h=0.5, alpha=1 (n_hidden=N); lr=0.08, reg=0.05, n_samples=200, iter=100 matched across every series",
        y=1.04, fontsize=10.5
    )
    fig.tight_layout()
    _save(fig, f"fig10_ite_tte_vs_n_all_solvers_eps{epsilon:g}")


def _save(fig, name):
    os.makedirs(OUT_DIR, exist_ok=True)
    for ext in ("png", "pdf"):
        path = os.path.join(OUT_DIR, f"{name}.{ext}")
        fig.savefig(path, dpi=150 if ext == "png" else None, bbox_inches="tight")
        print(f"wrote {path}")
    plt.close(fig)


if __name__ == "__main__":
    fig1_ite_vs_n_tfim1d()
    fig2_tte_vs_n_velox_fpga()
    fig3_energy_to_solution_vs_n()
    fig4_success_fraction_heisenberg()
    fig5_convergence_dwave_tfim1d()
    fig6_energy_vs_n_tfim2d_dwave()
    fig7_classical_scaling_tfim1d()
    fig8_all_solvers_n16()
    fig9_ite_tte_all_solvers_n16()
    fig10_ite_tte_vs_n_all_solvers()
